name: Deploy Firebase API
on:
    push:
        branches:
        - main
        paths:
        - "api/plugin-firebase-api/**"

jobs:
    deploy:
      environment: prod
      runs-on: ubuntu-latest
      outputs:
        IMAGE_TAG: ${{ steps.determine-image-tag.outputs.IMAGE_TAG }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - id: "auth"
          uses: "google-github-actions/auth@v2"
          with:
            credentials_json: "${{ secrets.TERRAFORM_SERVICE_ACCOUNT_KEY }}"
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: "Set up Cloud SDK"
          uses: "google-github-actions/setup-gcloud@v1"

        - name: Configure Docker
          run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

        - name: Use NPM to install dependencies
          uses: actions/setup-node@v1
          with:
            node-version: "20.x"
        - run: npm install

        - name: Build application
          run: npm run build

        - name: Determine Image Tag
          id: determine-image-tag
          run: |
            IMAGE_TAG=0.0.${{ github.run_number }}
            echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
            echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

        - name: Build Docker image
          run: docker build -f Dockerfile -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plugin-firebase-api/plugin-firebase-api:$IMAGE_TAG .

        - name: Push Docker image
          run: docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plugin-firebase-api/plugin-firebase-api:$IMAGE_TAG

        - name: Deploy Docker image
          run: gcloud run deploy plugin-firebase-api --image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plugin-firebase-api/plugin-firebase-api:$IMAGE_TAG --platform managed --region ${{ vars.GCP_REGION }} --allow-unauthenticated --min-instances 1 --max-instances 2 \--memory 128Mi --cpu 1 --port 3000 --service-account=${{ secrets.CLOUD_RUN_EXECUTOR_SERVICE_ACCOUNT }}
